### ISSUE TITLE
bug#1: Login Background clipping to dashboard

### ISSUE THREAD

**Issue by chrisEsk** [softstewCenfo/petButler#32]
Dashboard -> iniciar sesión -> [BACK] -> [FORWARD]

Background de login (morado) se mete en el background de la applicación.

HU-DM-5 (Iniciar Sesión) - @JJM100

**Comment by JJM100** [comment]
Este issue no es tan importante lo arreglo después del jueves para concentrarme en las otras funcionalidad para la presentación.
