### ISSUE TITLE
MC: Link a crm...

### ISSUE THREAD

**Issue by marito8833** [softstewCenfo/petButler#38]
El siguiente link: "PetButler is a Softew company"  
![buggylink](https://cloud.githubusercontent.com/assets/5726525/8613717/403c509a-269f-11e5-93c2-6e8b4c3f2182.png)
en la página de login redirige a está página: http://www.salesforce.com/mx/?ir=1
![pageimage](https://cloud.githubusercontent.com/assets/5726525/8613686/c9c84a18-269e-11e5-8a44-b81cebccd94b.png)

**Comment by JJM100** [comment]
Pura Vida! Ya lo arregle
