### ISSUE TITLE
HU-TD-14 Correo o nombre de usuario 

### ISSUE THREAD

**Issue by marito8833** [softstewCenfo/petButler#40]
El ingresar el usuario **b** y la contraseña **b** y presionar la tecla enter me redirige al index de la aplicación. No ingreso a la cuenta, **no me da retroalimentación de que no existe el usuario**.

**Comment by JJM100** [comment]
![screen shot 2015-07-12 at 10 36 36 am](https://cloud.githubusercontent.com/assets/4322846/8638745/e9c1ab90-2881-11e5-8c33-bced29335e71.png)

**Comment by JJM100** [comment]
![screen shot 2015-07-12 at 10 37 20 am](https://cloud.githubusercontent.com/assets/4322846/8638749/012b8134-2882-11e5-8193-21945cf1b843.png)
