### ISSUE TITLE
HU-TD-14 Contraseña no es validada

### ISSUE THREAD

**Issue by marito8833** [softstewCenfo/petButler#41]
Puedo ingresar con el usuario **admin@petbutler.com** y la contraseña **f** o **cublar** . No importa la contraseña que digite, igual ingreso como ese usuario si existe.

**Comment by JJM100** [comment]
![screen shot 2015-07-12 at 10 35 30 am](https://cloud.githubusercontent.com/assets/4322846/8638739/c8b13c36-2881-11e5-8cc4-746cec30f4ea.png)
